### ISSUE TITLE
Sphinx has no module "sphinx_setup.command"

### ISSUE THREAD

**Issue by dapi115** [monzelr/dmx#3]
I found no solution for this error:

`
pi@ola:~/dmx $ pip3 install .
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing /home/pi/dmx
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /tmp/tmps9usjuq4_in_process.py get_requires_for_build_wheel /tmp/tmpta2n02m0
       cwd: /tmp/pip-req-build-d23qjsp4
  Complete output (15 lines):
  Traceback (most recent call last):
    File "/tmp/tmps9usjuq4_in_process.py", line 280, in <module>
      main()
    File "/tmp/tmps9usjuq4_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/tmp/tmps9usjuq4_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-1loa7x9a/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-1loa7x9a/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-1loa7x9a/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 311, in run_setup
      exec(code, locals())
    File "<string>", line 51, in <module>
  ModuleNotFoundError: No module named 'sphinx.setup_command'
  ----------------------------------------
WARNING: Discarding file:///home/pi/dmx. Command errored out with exit status 1: /usr/bin/python3 /tmp/tmps9usjuq4_in_process.py get_requires_for_build_wheel /tmp/tmp                  ta2n02m0 Check the logs for full command output.
ERROR: Command errored out with exit status 1: /usr/bin/python3 /tmp/tmps9usjuq4_in_process.py get_requires_for_build_wheel /tmp/tmpta2n02m0 Check the logs for full command output.
`

**Comment by dapi115** [comment]
The solution is to install sphinx Version 5.0.0

**Comment by monzelr** [comment]
This problem is fixed in version 0.2.3.
